apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dr-region
  labels:
    app: backend
    region: dr
spec:
  selector:
    app: backend
    region: dr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
