apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaniSaed/smart-retail-config.git
    targetRevision: main
    path: k8s/dr-region/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: dr-region
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
