apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dr-region
  labels:
    app: frontend
    region: dr
spec:
  selector:
    app: frontend
    region: dr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
