

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogo-jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"         # Jenkins UI
      - "50000:50000"       # Jenkins Agent communication
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kubeconfig:/var/jenkins_home/kubeconfig-static  # כאן תשמור את הקובץ kubeconfig
    privileged: true
    networks:
      - gogo-net

networks:
  gogo-net:
    driver: bridge
