pipeline {
  agent any

  environment {
    IMAGE_NAME = 'rani19/backend'
    TAG = 'latest'
    DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
    DEV_REPO_URL = 'https://github.com/RaniSaed/smart-retail-dev.git'
  }

  stages {
    stage('Clone Dev Repo') {
      steps {
        echo 'Cloning smart-retail-dev repository...'
        dir('dev') {
          git url: "${DEV_REPO_URL}", branch: 'main'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        echo 'Building Docker image from backend code...'
        dir('dev/backend') {
          script {
            sh 'docker build -t ${IMAGE_NAME}:${TAG} .'
          }
        }
      }
    }
  }
}
