pipeline {
  agent any

  environment {
    IMAGE_NAME = 'rani19/backend'
    TAG = "build-${env.BUILD_NUMBER}"
    DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
    DEV_REPO_URL = 'https://github.com/RaniSaed/smart-retail-dev.git'
  }

  stages {
    stage('Clone Dev Repo') {
      steps {
        echo '📥 Cloning smart-retail-dev repository...'
        dir('dev') {
          git url: "${DEV_REPO_URL}", branch: 'main'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        echo '🐳 Building Docker image...'
        dir('dev/backend') {
          script {
            docker.build("${IMAGE_NAME}:${TAG}")
          }
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        echo '🚀 Pushing Docker image to Docker Hub...'
        dir('dev/backend') {
          script {
            docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
              docker.image("${IMAGE_NAME}:${TAG}").push()
              docker.image("${IMAGE_NAME}:${TAG}").push('latest')
            }
          }
        }
      }
    }
  }

  post {
    success {
      echo '✅ Build and Push succeeded!'
    }
    failure {
      echo '❌ Build and Push failed.'
    }
  }
}
